name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Test Reporting XML
        uses: phoenix-actions/test-reporting@v12
        id: test-report-xml # Set ID reference for step
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Playwright Tests result # Name of the check run which will be created
          path: test-results/report*.xml # Path to test results
          reporter: java-junit # Format of test results
      - name: Test Reporting JSON
        uses: phoenix-actions/test-reporting@v12
        id: test-report-json # Set ID reference for step
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Playwright Tests result # Name of the check run which will be created
          path: test-results/report*.json # Path to test results
          reporter: mocha-json # Format of test results
